{% set name = "graphormer-pretrained" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphormer-pretrained-{{ version }}.tar.gz
  sha256: 7fff527532743d7bbb060b474e0ef9c750dd5a34b543c64bfdd2b26defb5e407

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - tqdm
    - gcsfs
    - pytorch >=1.10.2
    - pytorch_geometric
    - ogb
    - tensorboardx
    - fairseq >=0.12.3
    - python-lmdb
    - datamol
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - graphormer_pretrained
  source_files:
    - tests/
  commands:
    - pytest --verbose tests/

about:
  home: https://github.com/maclandrol/graphormer-pretrained
  summary: Packaging of Graphormer is a deep learning package by Microsoft that allows researchers and developers to train custom models for molecule modeling tasks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
